var board = document.getElementById("mytext");
board.innerHTML = "'This text is generated by javascript. Home/Index'";

var jumb = document.getElementById("jumbotron");
jumb.style.backgroundColor = 'lightcyan';